backend:
  name: git-gateway
  branch: main 

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images"

collections:
  - name: "products" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/markdown" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/product.astro"}
      - {label: "Title", name: "name", widget: "string"}
      - { label: "Tags", name: "tag", widget: "list", default: "computer" }
      - {label: "Featured Image", name: "img", widget: "image"}
      - {label: "Body", name: "description", widget: "markdown"}
      - {label: "Specs", name: "specs", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
